# -*- coding: utf-8 -*-
"""python guessing game

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FVtSYX5g8lN6xNhE6kgmmMvn-9-OpL_h
"""

import random 
# library that we use in order to choose 
# on random words from a list of words 

name = input("What is your name? ") 
# Here the user is asked to enter the name first 
print("the objectives of the game is to guess the name of the cricketer given below selected randomly to win.")
print("Good Luck ! ", name) 

players = ['M.S. Dhoni', 'Virat Kohli', 'Sachin Tendulkar', 'Ravindra Jadeja', 
		'Yuzvendra Chahal', 'Ravichandran Ashwin', 'Yuvraj Singh', 'Shikhar Dhawan', 
		'Sunil Gavaskar', 'Hardik Pandya', 'Mohammed Shami', 'Rahul Dravid'] 
print("Players = ", players)
# Function will choose one random 
# word from this list of words 
word = random.choice(players) 


print("Guess the characters") 

guesses = '' 

# any number of turns can be used here 
turns = 12


while turns > 0: 
	
	# counts the number of times a user fails 
	failed = 0
	
	# all characters from the input 
	# word taking one at a time. 
	for char in word: 
		
		# comparing that character with 
		# the character in guesses 
		if char in guesses: 
			print(char) 
			
		else: 
			print("_") 
   	# for every failure 1 will be 
			# incremented in failure 
			failed += 1
			

	if failed == 0: 
		# user will win the game if failure is 0 
		# and 'You Win' will be given as output 
		print("Eureka!!!.....You Win") 
		
		# this print the correct word 
		print("The word is: ", word) 
		break
	

	
	# if user has input the wrong alphabet then 
	# it will ask user to enter another alphabet 
	guess = input("guess a character:") 
	
	# every input character will be stored in guesses 
	guesses += guess 
	
	# check input with the character in word 
	if guess not in word: 
		
		turns -= 1
		
		# if the character doesn’t match the word 
		# then “Wrong” will be given as output 
		print("Wrong") 
		
		# this will print the number of 
		# turns left for the user 
		print("You have", + turns, 'more guesses') 
		
		
		if turns == 0: 
			print("Kiddo ...You Loose")